development:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL']
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['TEST_DATABASE_URL'] %>
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
